services:
  maven-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - build-artefacts:/opt/oxo:rw
      - ${M2_VOLUME}:/root/.m2/repository:rw
  dataload:
    build:
      context: .
      dockerfile: ./oxo2-dataload/dataload.Dockerfile
    depends_on:
      - maven-build
    volumes:
      - build-artefacts:/opt/oxo:rw
      - ./${OXO_CONFIG:?OXO dataload requires a config file}:/mnt/config/${OXO_CONFIG}:ro
volumes:
  maven-repo:
  build-artefacts:
