apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
spec:
  replicas: {{ .Values.solr.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      securityContext:
        fsGroup: 8389
        runAsUser: 8389
        runAsGroup: 8389
        runAsNonRoot: true     
      containers:
        - name: solr
          image: docker.io/library/solr:9.9.0
          env:
            - name: SOLR_HOME
              value: /var/solr
          ports:
            - containerPort: {{ .Values.solr.service.containerPort }}
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-solr-pvc
          
