apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-solr-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.solr.persistence.size }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/solr-data
    type: Directory
  {{- if .Values.solr.persistence.nodeAffinity.host }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.solr.persistence.nodeAffinity.host | quote }}
  {{- end }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-solr-pvc