apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxo2.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "oxo2.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "oxo2.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image | quote }}
          env:
            - name: OXO2_SOLR_HOST
              value: "http://{{ include "oxo2.fullname" . }}-solr:{{ .Values.solr.port }}/solr"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}