apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxo2.fullname" . }}-backend
spec:
  selector:
    app: {{ include "oxo2.fullname" . }}-backend
  ports:
    - port: {{ .Values.backend.containerPort }}
      targetPort: {{ .Values.backend.containerPort }}
  type: ClusterIP