apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxo2.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "oxo2.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "oxo2.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image | quote }}
          env:
            - name: BACKEND_API_URL
              value: "http://{{ include "oxo2.fullname" . }}-backend:{{ .Values.backend.containerPort }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}