apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: {{ .Release.Name }}-solr-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.solr.persistence.size }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/local-disk  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hh-rke-wp-webadmin-56-worker-1.caas.ebi.ac.uk
  volumeMode: Filesystem        
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-solr-pvc