apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
spec:
  replicas: {{ .Values.solr.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000  
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /var/solr']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr           
      containers:
        - name: solr
          image: docker.io/library/solr:9.9.0
          env:
            - name: SOLR_HOME
              value: /var/solr
          ports:
            - containerPort: {{ .Values.solr.service.containerPort }}
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-solr-pvc
          
