apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oxo2.fullname" . }}-solr-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.solr.persistence.size }}