apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oxo2.fullname" . }}-solr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.solr.persistence.size }}