apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxo2.fullname" . }}-solr
spec:
  selector:
    app: {{ include "oxo2.fullname" . }}-solr
  ports:
    - port: {{ .Values.solr.port }}
      targetPort: {{ .Values.solr.port }}
  type: ClusterIP