# Build all oxo2 modules
FROM maven:3.9.10-eclipse-temurin-17 AS build

RUN getent group 1001 || addgroup --gid 1001 oxo
RUN id -u oxo || adduser --uid 1001 --gid 1001 oxo

RUN mkdir -p /opt/oxo && chmod 770 /opt/oxo && chown oxo:oxo /opt/oxo
WORKDIR /opt/oxo

USER oxo
RUN mkdir oxo2-shared oxo2-dataload

COPY ./pom.xml /opt/oxo/
COPY ./oxo2-shared/ /opt/oxo/oxo2-shared/
COPY ./oxo2-dataload/ /opt/oxo/oxo2-dataload/

USER root
RUN chown -R oxo:oxo /opt/oxo/*

USER oxo
RUN --mount=type=cache,target=/root/.m2 \
    cd /opt/oxo/oxo2-shared/ && mvn clean package install && \
    cd /opt/oxo/oxo2-dataload/ && mvn clean package install

# Create image for oxo2-dataload
FROM eclipse-temurin:17-alpine

RUN getent group 1001 || (addgroup --system --gid 1001 oxo || (echo "Failed to create group oxo with GID 1000" && exit 1)) \
 && id -u 1001 || (adduser --system --uid 1001 --ingroup oxo oxo || (echo "Failed to create user oxo with UID 1000" && exit 1))

RUN mkdir -p /opt/oxo && chmod 770 /opt/oxo && chown oxo:oxo /opt/oxo
WORKDIR /opt/oxo
USER oxo
RUN mkdir oxo2-dataload &&  \
    cd oxo2-dataload &&  \
    mkdir oxo2-downloader oxo2-json2inferences oxo2-sssom2json &&  \
    mkdir oxo2-downloader/target oxo2-json2inferences/target oxo2-sssom2json/target

COPY ./oxo2-dataload/*.sh ./oxo2-dataload/*.dockersh /opt/oxo/oxo2-dataload/
USER root
RUN chown oxo:oxo /opt/oxo/oxo2-dataload/*
USER oxo
RUN chmod +x /opt/oxo/oxo2-dataload/*.sh &&  \
    chmod +x /opt/oxo/oxo2-dataload/dataload.dockersh && \
    mkdir /tmp/out

COPY --from=build /opt/oxo/oxo2-dataload/oxo2-downloader/target/oxo2-downloader-1.0.0-SNAPSHOT.jar ./oxo2-downloader/target
COPY --from=build /opt/oxo/oxo2-dataload/oxo2-sssom2json/target/oxo2-sssom2json-1.0.0-SNAPSHOT.jar ./oxo2-sssom2json/target


# Ensure dataload.dockersh is executable
#RUN

#WORKDIR /opt/oxo/oxo2-dataload
WORKDIR /opt/oxo/oxo2-shared

#CMD ./dataload.dockersh
CMD ls -al