apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxo2-logs
  namespace: ontotools
spec:
  storageClassName: standard-nfs-production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
