apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: web
          image: ghcr.io/ebispot/oxo2:{{.Values.imageTag}}
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
              cpu: 0.25
            limits:
              memory: 1Gi
              cpu: 0.5
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: oxo2-env
          command: ["/bin/bash", "-c"]
          args: ["/opt/oxo2/entrypoint.dockersh"]