apiVersion: v1
kind: ConfigMap
metadata:
  name: oxo2-env
  labels:
    app: {{.Values.name}}
data:
  PUBLIC_URL: /spot/oxo2
  REACT_APP_SSSOM_API: http://66.29.128.20:8008
  REACT_APP_SSSOM_HOME: https://mapping-commons.github.io/sssom/spec/
  REACT_APP_EBI_LICENSING: https://www.ebi.ac.uk/licencing
  REACT_APP_EBI_HOME: https://www.ebi.ac.uk
  REACT_APP_SPOT_ONTOTOOLS: https://www.ebi.ac.uk/spot/ontology/
  REACT_APP_SPOT_ZOOMA: https://www.ebi.ac.uk/spot/zooma
  REACT_APP_SPOT_OXO_CONTACT: https://www.ebi.ac.uk/spot/oxo/contact
  REACT_APP_SPOT_OXO2_REPO: https://github.com/EBISPOT/oxo2
  REACT_APP_SPOT_OLS_ANNOUNCE: https://listserver.ebi.ac.uk/mailman/listinfo/ols-announce
  REACT_APP_SPOT_OLS4: https://www.ebi.ac.uk/ols4
  REACT_APP_NLM_UMLS: https://www.nlm.nih.gov/research/umls
