apiVersion: v2
name: oxo2
description: oxo2 deployment (solr, backend, frontend)
type: application
# Chart package version Helm uses (must follow semver). It identifies the chart release in repos, is used for
# installs/upgrades and dependency resolution (.Chart.Version).
version: 0.1.0
# Tthe version of the application the chart installs (informational/freeform). It is shown to users and can be used in
# templates (.Chart.AppVersion) but Helm does not use it for upgrade logic.
appVersion: "1.0"