replicaCount: 1

solr:
  image: "solr:9.9.0"
  port: 8983
  persistence:
    enabled: true
    size: 5Gi

backend:
  image: "oxo2/backend:dev"
  containerPort: 8080

frontend:
  image: "oxo2/frontend:dev"
  containerPort: 8081
  service:
    type: NodePort
    port: 8081
    nodePort: 30081

