name: Build and push OxO2 images

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}    

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
      
    if: ${{ github.repository_owner == 'EBISPOT' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push OxO2 dataload Docker image
        run: |
          docker build -t ghcr.io/ebispot/oxo2-dataload:${{ github.sha }} -f ./oxo2-dataload/dataload.Dockerfile .
          docker tag ghcr.io/ebispot/oxo2-dataload:${{github.sha}} ghcr.io/ebispot/oxo2-dataload:${{ github.head_ref || github.ref_name }}
          docker push --all-tags ghcr.io/ebispot/oxo2-dataload

      - name: Build and push OxO2 backend Docker image
        run: |
          docker build -t ghcr.io/ebispot/oxo2-backend:${{ github.sha }} -f ./oxo2-backend/backend.Dockerfile .
          docker tag ghcr.io/ebispot/oxo2-backend:${{github.sha}} ghcr.io/ebispot/oxo2-backend:${{ github.head_ref || github.ref_name }}
          docker push --all-tags ghcr.io/ebispot/oxo2-backend

      - name: Build and push OxO2 frontend Docker image
        run: |
          cd oxo2-frontend
          docker build -t ghcr.io/ebispot/oxo2-frontend:${{ github.sha }} -f frontend.Dockerfile .
          docker tag ghcr.io/ebispot/oxo2-frontend:${{github.sha}} ghcr.io/ebispot/oxo2-frontend:${{ github.head_ref || github.ref_name }}
          docker push --all-tags ghcr.io/ebispot/oxo2-frontend          
          
